<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Interfaces\IManagers\" />
    <Folder Include="Interfaces\IRepositories\" />
    <Folder Include="Managers\" />
    <Folder Include="Mapping\" />
    <Folder Include="Models\" />
  </ItemGroup>

</Project>
